site_name: RestAction
pages:
  - Home: index.md
  - Quickstart: quickstart.md
  - Schema: schema.md
  - resjs: resjs.md
  - Document: document.md
  - API: api.autodoc
  - Language: language.md
theme: yeti
extra_css:
  - css/extra.css
markdown_extensions:
  - def_list
  - admonition
repo_url: 'https://github.com/guyskk/flask-restaction'
